### ISSUE TITLE
Word Core 2016 - Lesson 2 - Learn to cut, copy and paste - Task 4: Close without saving

### ISSUE THREAD

**Issue by LeeJohnSolda** [ccilearning/Office-2016#12]
Still not scoring after trying it again on Office PP2016 Remote Desktop Dan. Lee

**Comment by ccidan** [comment]
Lee - can you test this lesson, it should be scoring correctly now.

**Comment by LeeJohnSolda** [comment]
So strange Dan! I've tried to score this 3 times so far today (once on the Multi-Channel Remote PC, Once on the Semi-Annual PC and the 3rd time thru on my own Laptop) and I'm still not scoring the 'Close without Saving' part!  👎

**Comment by mlankin** [comment]
Scoring Correctly.

Preview in the lesson does not match actual writing in the file. 
![2019-01-18_9-25-15](https://user-images.githubusercontent.com/45178808/51402763-43ed7c80-1b03-11e9-9eeb-06b8935054f2.png)
