### ISSUE TITLE
Word Core 2016 - Create Exercise - Changing the Margins - Change custom margin

### ISSUE THREAD

**Issue by mlankin** [ccilearning/Office-2016#17]
The error is on Microsoft Office 365 ProPlus.

[Testing create Apollo 11 activity (1).docx](https://github.com/ccidan/Office-2016/files/2634359/Testing.create.Apollo.11.activity.1.docx)

**Comment by mlankin** [comment]
Reported by Brenda Valdez at Ballou Junior High School

**Comment by ccidan** [comment]
Submitted to ETC for review

**Comment by ccidan** [comment]
Word Core 2016 - Create Exercise - Changing the Margins - Change custom margin> The problem was corrected
Is necessary a new version.

**Comment by LeeJohnSolda** [comment]
Tested this on the Remote Office 2016 PP machine and JA v.1.1.2.4 and scored it correctly. I tested it using the Word Doc that was provided originally by MLankin back on Nov 30, 2018 - attached below:

![word core 2016_create_exercise_report-change custom margin](https://user-images.githubusercontent.com/45051658/51496832-0b090e00-1d76-11e9-88f2-29cd481f501f.JPG)
[Testing.create.Apollo.11.activity.1.5.docx](https://github.com/ccilearning/Office-2016/files/2780389/Testing.create.Apollo.11.activity.1.5.docx)
