### ISSUE TITLE
Excel Expert 2016 - Lesson 6 - Copying Macros

### ISSUE THREAD

**Issue by ccidan** [ccilearning/Office-2016#18]
Sent to ETC for Review - Copy Macro to another Workbook is not scoring on Office Pro Plus 2016

**Comment by LeeJohnSolda** [comment]
Attempted this 3 times on the Office 2016 ProPlus Remote MCT machine and still scored incorrectly the Copy Macros to another Workbook portion and the version of Jasperactive that was used was Version 1.1.2.4

**Comment by LeeJohnSolda** [comment]
Attempted this 3 times on the Office 2016 ProPlus Remote MCT machine and still scored incorrectly the Copy Macros to another Workbook portion and the version of Jasperactive that was used was Version 1.1.2.4
